### ISSUE TITLE
RSML - Addition of "Create Primary Root" Functionality in RSML Expert

### ISSUE THREAD

**Issue by LGPolytech** [Rocsg/RootSystemTracker#2]
J’ai des séries d’images où la détection de la racine primaire par RootSystemTracker a échoué, et du coup j’ai 0 donnée d’architecture car il manque toute la plante, et je ne peux pas rattraper avec RSML expert, car c’est pas juste des « branch » à rajouter, mais c’est toute la plante avec la racine primaire que j’ai besoin de recréer.

**Comment by Rocsg** [comment]
Des discussions avec l'utilisateur, il est sorti qu'on n'a pas forcément besoin d'un bouton en plus, mais que l'aspect racine primaire, secondaire ou d'ordre 3 peut etre determiné tout seul : Si le premier point est positionné à proximité d'un axe existant (mettons à une distance inférieure à un seuil fixe, ou determiné en fonction de la résolution de l'image), alors c'est que ce nouvel axe est un sous-axe de l'axe concernée. Sinon, si il est plus loin que ce seuil (un axe isolé), c'est assurémen un nouvel axe, et donc une racine primaire, et donc une nouvelle plante. Ce schéma devra être adapté aux nouvelles données arrivant (plus complexe qu'arabido).
